// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Cip83Tilyji5ZcB_sfF3wAwLTMQ1-7U',
    appId: '1:437178302072:web:67c1b74668e0c951e9f78d',
    messagingSenderId: '437178302072',
    projectId: 'bixcinema',
    authDomain: 'bixcinema.firebaseapp.com',
    storageBucket: 'bixcinema.firebasestorage.app',
    measurementId: 'G-YH518ST57N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr3t2zx30FR4HeECCJWb8PL7OA4M9uZ1A',
    appId: '1:437178302072:android:7a14bfe88e292a74e9f78d',
    messagingSenderId: '437178302072',
    projectId: 'bixcinema',
    storageBucket: 'bixcinema.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbjQxY9xDgvhNzKK-NCvQZ0sAxPan7Jcc',
    appId: '1:437178302072:ios:b24be28ef5b881f2e9f78d',
    messagingSenderId: '437178302072',
    projectId: 'bixcinema',
    storageBucket: 'bixcinema.firebasestorage.app',
    iosBundleId: 'com.example.belajarappdart1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbjQxY9xDgvhNzKK-NCvQZ0sAxPan7Jcc',
    appId: '1:437178302072:ios:b24be28ef5b881f2e9f78d',
    messagingSenderId: '437178302072',
    projectId: 'bixcinema',
    storageBucket: 'bixcinema.firebasestorage.app',
    iosBundleId: 'com.example.belajarappdart1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Cip83Tilyji5ZcB_sfF3wAwLTMQ1-7U',
    appId: '1:437178302072:web:b8c280d07270a6cde9f78d',
    messagingSenderId: '437178302072',
    projectId: 'bixcinema',
    authDomain: 'bixcinema.firebaseapp.com',
    storageBucket: 'bixcinema.firebasestorage.app',
    measurementId: 'G-8DR5QD842Y',
  );
}
